spring:
  application:
    name: employee-svc
  datasource:
    url: jdbc:h2:file:./data/employee-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  kafka:
    bootstrap-servers: localhost:9092
    kafka:
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
      consumer:
        group-id: employee-processors
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

resilience4j:
  circuitbreaker:
    instances:
      departmentService:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
  retry:
    instances:
      retryDepartmentService:
        max-attempts: 3
        wait-duration: 500ms
  bulkhead:
    instances:
      bulkheadDepartmentService:
        max-concurrent-calls: 20
        max-wait-duration: 0
  ratelimiter:
    instances:
      ratelimiterDepartmentService:
        limit-for-period: 10
        limit-refresh-period: 1s
        timeout-duration: 0
logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false
  
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    export:
      zipkin:
        endpoint: http://localhost:9411/api/v2/spans
    sampling:
      probability: 1.0